export const walletOne = [
  {
    id: 2,
    sym: "erc20",
    name: "Ethereum",
    address: "0xc4e43bb957cfc4e8f2c80a104d0c3041ab3729d4",
    network: "Eth",
    img: "/wallets/eth.jpeg",
  },
  {
    id: 3,
    sym: "usdt bep20",
    name: "Tether bep20",
    address: "0xc4e43bb957cfc4e8f2c80a104d0c3041ab3729d4",
    network: "usdt-bep20",
    img: "/wallets/bep20.jpeg",
  },
  {
    id: 4,
    sym: "usdt trc",
    name: "Tether Trc",
    address: "TZBFHCXXfjaSybhkFQ3T315sbEAxnxvmdq",
    network: "usdt-trc",
    img: "/wallets/usdt.jpeg",
  },
  {
    id: 1,
    sym: "btc",
    name: "Bitcoin",
    address: "3QZ4CNpHSWMnG4P7LzX72gxHrQFpDr4Etx",
    network: "BTC",
    img: "/wallets/btc.jpeg",
  },
  {
    id: 5,
    sym: "ltc",
    name: "Litecoin",
    address: "LRAKP6FZ8YLtJd9tcy4dzbsSBk6u4FHDTT",
    network: "litecoin",
    img: "/wallets/ltc.jpeg",
  },
];

export const walletTwo = [
  {
    id: 2,
    sym: "erc20",
    name: "Ethereum",
    address: "0xc4e43bb957cfc4e8f2c80a104d0c3041ab3729d4",
    network: "Eth",
    img: "/wallets/eth.jpeg",
  },
  {
    id: 3,
    sym: "usdt bep20",
    name: "Tether bep20",
    address: "0xc4e43bb957cfc4e8f2c80a104d0c3041ab3729d4",
    network: "usdt-bep20",
    img: "/wallets/bep20.jpeg",
  },
  {
    id: 4,
    sym: "usdt trc",
    name: "Tether Trc",
    address: "TZBFHCXXfjaSybhkFQ3T315sbEAxnxvmdq",
    network: "usdt-trc",
    img: "/wallets/usdt.jpeg",
  },
  {
    id: 1,
    sym: "btc",
    name: "Bitcoin",
    address: "3QZ4CNpHSWMnG4P7LzX72gxHrQFpDr4Etx",
    network: "BTC",
    img: "/wallets/btc.jpeg",
  },
  {
    id: 5,
    sym: "ltc",
    name: "Litecoin",
    address: "LRAKP6FZ8YLtJd9tcy4dzbsSBk6u4FHDTT",
    network: "litecoin",
    img: "/wallets/ltc.jpeg",
  },
];
